baseURL = "https://whereimreallyfrom.github.io"
languageCode = "en-us"
title = "Where I'm Really From"
theme = "persian"
pygmentscodefences  = true
pygmentsUseClasses = true

[params]
    author = "Robin Zeng"
    sitename = "Where I'm Really From"
    description = "An archive"
    githubUsername = "whereimreallyfrom"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Source Sans Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "xcode"
    highlightLanguages = ["rust", "cpp", "python", "golang"]
    katexVersion = "0.11.1"

[[menu.main]]
    url = "/about/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 2

[[menu.main]]
    url = "https://github.com/whereimreallyfrom"
    name = "Github"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
